# Generated by Django 2.1.3 on 2018-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='alias',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='alias',
            field=models.CharField(max_length=12),
        ),
    ]
