# Generated by Django 2.1.3 on 2018-11-29 21:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Valor MAC incorrecto', regex='^[0-9a-fA-F]*$')], verbose_name='MAC Address')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Valor MAC incorrecto', regex='^[0-9a-fA-F]*$')], verbose_name='MAC Address')),
                ('alias', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Valor MAC incorrecto', regex='^[0-9a-fA-F]*$')], verbose_name='MAC Address')),
                ('tipo', models.IntegerField(choices=[(1, 'Wifi'), (2, 'Bluetooth')], default=1)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('deteccion', models.DateTimeField(auto_now_add=True)),
                ('deauth', models.BooleanField(default=False)),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Valor MAC incorrecto', regex='^[0-9a-fA-F]*$')], verbose_name='MAC Address')),
                ('alias', models.CharField(blank=True, max_length=12, null=True)),
                ('app', models.FileField(blank=True, null=True, upload_to='', verbose_name='Software image')),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contact_id', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Receptores',
                'verbose_name': 'Receptor',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Nodo'),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['mac'], name='mac_blk_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['mac'], name='mac_alert_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['mac'], name='mac_det_idx'),
        ),
    ]
